monday_am = float(input('What time did you arrive on Monday?'))
monday_pm = float(input('What time did you leave on Monday?'))
monday_lunch = float(input('Did you take any time off for lunch?'))
mon = 12-monday_am + monday_pm - monday_lunch
tuesday_am = float(input('What time did you arrive on Tuesday?'))
tuesday_pm = float(input('What time did you leave on Tuesday?'))
tuesday_lunch = float(input('Did you take any time off for lunch?'))
tue = 12-tuesday_am + tuesday_pm - tuesday_lunch
wednesday_am = float(input('What time did you arrive on Wednesday?'))
wednesday_pm = float(input('What time did you leave on Wednesday?'))
wednesday_lunch = float(input('Did you take any time off for lunch?'))
wed = 12-wednesday_am + wednesday_pm - wednesday_lunch
thursday_am = float(input('What time did you arrive on Thursday?'))
thursday_pm = float(input('What time did you leave on Thursday?'))
thursday_lunch = float(input('Did you take any time off for lunch?'))
thur = 12-thursday_am + thursday_pm - thursday_lunch
friday_am = float(input('What time did you arrive on Friday?'))
friday_pm = float(input('What time did you leave on Friday?'))
friday_lunch = float(input('Did you take any time off for lunch?'))
fri = 12-friday_am + friday_pm - friday_lunch
print('Monday ', mon, ', Tuesday ', tue, ', Wednesday ', wed, ', Thursday ', thur, ', Friday', fri)